### ISSUE TITLE
original-cliの概要

### ISSUE THREAD

**Issue by R-Mizuguchi** [R-Mizuguchi/original-cli#1]
@g8e9-ae
[README.md](https://github.com/R-Mizuguchi/original-cli#original-cli-%E9%A3%B2%E9%A3%9F%E5%BA%97%E8%87%AA%E5%8B%95%E6%8F%90%E6%A1%88%E3%83%84%E3%83%BC%E3%83%AB)にoriginal-cliの概要を追記しました！

よろしくお願いします！

**Comment by g8e9-ae** [comment]
1.

技術的にはどのようなことをやるのでしょうか？

**Comment by R-Mizuguchi** [comment]
> 技術的にはどのようなことをやるのでしょうか？

基本的にはGoogleのAPIを使って、位置情報、近くの飲食店等を情報として取得して、受け取った情報を元にデータをランダムに抽出して標準出力するという構想です。

**Comment by g8e9-ae** [comment]
まず、APIと通信するというツールは、

- 動作確認ができる状態にしなければいけない
- コード量が増えないため、場合によってはあまりいいお題にならない

というデメリットがあるのですが、それでもよければ、進めてもらって大丈夫です。

**Comment by R-Mizuguchi** [comment]
> コード量が増えないため、場合によってはあまりいいお題にならない

このデメリットに関しては、少し要件を足すことによって解消したいと思います。
